export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  BAD_REQUEST: 'BAD_REQUEST',

  BEDROCK_ERROR: 'BEDROCK_ERROR',
  BEDROCK_RATE_LIMITED: 'BEDROCK_RATE_LIMITED',
  BEDROCK_MODEL_ERROR: 'BEDROCK_MODEL_ERROR',

  OPENSEARCH_ERROR: 'OPENSEARCH_ERROR',
  OPENSEARCH_CONNECTION_ERROR: 'OPENSEARCH_CONNECTION_ERROR',
  OPENSEARCH_INDEX_ERROR: 'OPENSEARCH_INDEX_ERROR',

  DYNAMODB_ERROR: 'DYNAMODB_ERROR',
  DYNAMODB_CONDITION_ERROR: 'DYNAMODB_CONDITION_ERROR',
  DYNAMODB_THROTTLING: 'DYNAMODB_THROTTLING',

  DOCUMENT_PROCESSING_ERROR: 'DOCUMENT_PROCESSING_ERROR',
  DOCUMENT_TOO_LARGE: 'DOCUMENT_TOO_LARGE',
  DOCUMENT_INVALID_FORMAT: 'DOCUMENT_INVALID_FORMAT',

  ANALYSIS_ERROR: 'ANALYSIS_ERROR',
  ANALYSIS_TIMEOUT: 'ANALYSIS_TIMEOUT',
  ANALYSIS_MODEL_ERROR: 'ANALYSIS_MODEL_ERROR',

  CHAT_SESSION_ERROR: 'CHAT_SESSION_ERROR',
  CHAT_MESSAGE_ERROR: 'CHAT_MESSAGE_ERROR',
  CHAT_CONTEXT_ERROR: 'CHAT_CONTEXT_ERROR',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.VALIDATION_ERROR]: 'Invalid input data provided',
  [ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.UNAUTHORIZED]: 'Authentication required',
  [ERROR_CODES.FORBIDDEN]: 'Access denied',
  [ERROR_CODES.CONFLICT]: 'Resource conflict detected',
  [ERROR_CODES.RATE_LIMITED]: 'Too many requests, please try again later',
  [ERROR_CODES.INTERNAL_ERROR]: 'Internal server error occurred',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',
  [ERROR_CODES.BAD_REQUEST]: 'Invalid request format',

  [ERROR_CODES.BEDROCK_ERROR]: 'AI service error occurred',
  [ERROR_CODES.BEDROCK_RATE_LIMITED]: 'AI service rate limit exceeded',
  [ERROR_CODES.BEDROCK_MODEL_ERROR]: 'AI model processing error',

  [ERROR_CODES.OPENSEARCH_ERROR]: 'Search service error occurred',
  [ERROR_CODES.OPENSEARCH_CONNECTION_ERROR]: 'Cannot connect to search service',
  [ERROR_CODES.OPENSEARCH_INDEX_ERROR]: 'Search index error',

  [ERROR_CODES.DYNAMODB_ERROR]: 'Database error occurred',
  [ERROR_CODES.DYNAMODB_CONDITION_ERROR]: 'Database condition check failed',
  [ERROR_CODES.DYNAMODB_THROTTLING]: 'Database request throttled',

  [ERROR_CODES.DOCUMENT_PROCESSING_ERROR]: 'Document processing failed',
  [ERROR_CODES.DOCUMENT_TOO_LARGE]: 'Document size exceeds limit',
  [ERROR_CODES.DOCUMENT_INVALID_FORMAT]: 'Unsupported document format',

  [ERROR_CODES.ANALYSIS_ERROR]: 'Analysis processing failed',
  [ERROR_CODES.ANALYSIS_TIMEOUT]: 'Analysis request timed out',
  [ERROR_CODES.ANALYSIS_MODEL_ERROR]: 'Analysis model error',

  [ERROR_CODES.CHAT_SESSION_ERROR]: 'Chat session error',
  [ERROR_CODES.CHAT_MESSAGE_ERROR]: 'Chat message processing error',
  [ERROR_CODES.CHAT_CONTEXT_ERROR]: 'Chat context retrieval error',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
